# Tests a broad set of Quarto functionality that users are likely to encounter.
# A failure indicates some signficant portion of functionality is likely to be broken.
name: Smoke Tests
on:
  workflow_call:
    inputs:
      buckets:
        description: "JSON string for buckets of tests to run in loop. Array of grouped tests."
        required: true
        type: string
      time-test:
        description: "Should we run tests to produce test file"
        required: false
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
      buckets:
        description: "JSON string for buckets of tests to run in loop. Array of grouped tests."
        required: false
        type: string
        default: ""
      time-test:
        description: "Should we run tests to produce test file"
        required: false
        type: boolean
        default: false
  schedule:
    - cron: "0 6 * * *"

jobs:
  run-smokes:
    name: Run smoke (${{ matrix.os }})${{ matrix.time-test && ' with timed file' || ''}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        time-test:
          - ${{ inputs.time-test }}
        exclude:
          # only run timed tests on Linux
          - os: windows-latest
            time-test: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          cache: "pipenv"
          cache-dependency-path: "./tests/Pipfile.lock"
          python-version-file: "./tests/.python-version"

      - name: Restore Python Dependencies
        working-directory: tests
        run: |
          python -m pip install pipenv
          pipenv install

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - run: ./configure.cmd
        shell: pwsh

      - run: ./run-tests.ps1 docs/smoke-all/jupyter/inline-execution-jupyter.qmd
        working-directory: tests
