# Upate the timing test file required for parallel test
on:
  workflow_dispatch:

name: Update timing test file

jobs:
  run-timed-tests:
    name: Running Tests to produce timed file
    uses: ./.github/workflows/test-smokes.yml
    with:
      buckets: ""
      time-test: true
